plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'io.rest-assured:rest-assured:5.3.0'
}

test {
    useJUnit()

    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
    }
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'